# Override para producción
# Usar con: docker compose -f deploy/docker-compose.yml -f config/production/docker-compose.override.yml

services:
  django:
    restart: always
    environment:
      DEBUG: "False"

