# Generated by Django 5.1.15 on 2026-03-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditPromptEdit',
        ),
    ]
